name: Build EXE with PyInstaller
Add commentMore actions

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.11'
          spec: 'index.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'index'
          options: --onedir, --windowed, --icon fow.ico
